### ISSUE TITLE
Upgrade to Driver 7.4 as ArabgoDB.Builder is no longer compatible

### ISSUE THREAD

**Issue by aburmeis** [arangodb/spring-boot-starter#25]
The current implementation of the `ArangoAutoConfiguration` is source but not compile compatible as the super class of the `ArangoDB.Builder` has been removed. This causes a `NoSuchMethodError` when any builder method is called:

````
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.arangodb.springframework.core.ArangoOperations]: Factory method 'arangoTemplate' threw exception with message: 'com.arangodb.internal.InternalArangoDBBuilder com.arangodb.ArangoDB$Builder.user(java.lang.String)'
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650)
	... 154 more
Caused by: java.lang.NoSuchMethodError: 'com.arangodb.internal.InternalArangoDBBuilder com.arangodb.ArangoDB$Builder.user(java.lang.String)'
	at com.arangodb.springframework.boot.autoconfigure.ArangoAutoConfiguration$ArangoBootConfiguration.arango(ArangoAutoConfiguration.java:59)
	at com.arangodb.springframework.config.ArangoConfiguration.arangoTemplate(ArangoConfiguration.java:47)
	at com.arangodb.springframework.boot.autoconfigure.ArangoAutoConfiguration$ArangoBootConfiguration$$SpringCGLIB$$0.CGLIB$arangoTemplate$7(<generated>)
	at com.arangodb.springframework.boot.autoconfigure.ArangoAutoConfiguration$ArangoBootConfiguration$$SpringCGLIB$$FastClass$$0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.arangodb.springframework.boot.autoconfigure.ArangoAutoConfiguration$ArangoBootConfiguration$$SpringCGLIB$$0.arangoTemplate(<generated>)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139)
````

A simple recompile with the upgraded dependency should help.

**Comment by aburmeis** [comment]
As an alternative, also the spring-data project can update the dependency and the starter use the new spring-data version.

**Comment by rashtao** [comment]
fixed in https://github.com/arangodb/spring-data/releases/tag/v4.0.1 and https://github.com/arangodb/spring-boot-starter/releases/tag/v3.1-2
